# version: '3.8'

# services:
#   app:
#     build: .
#     container_name: laravel-app
#     ports:
#       - "8080:80"
#     volumes:
#       - .:/var/www/html
#     networks:
#       - app-network
#     depends_on:
#       - db

#   db:
#     image: postgres:13
#     container_name: postgres
#     environment:
#       POSTGRES_DB: dbteste_wmug
#       POSTGRES_USER: root
#       POSTGRES_PASSWORD: 5g0uiB2k7xrEhWLfP75YknN77HkHqx70
#     ports:
#       - "5432:5432"
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge

# services:
#   - type: web
#     name: laravel-app
#     env: docker
#     plan: free
#     dockerfilePath: ./Dockerfile
#     buildCommand: composer install --no-dev --optimize-autoloader
#     startCommand: php artisan serve --host=0.0.0.0 --port=8000
#     envVars:
#       - key: APP_ENV
#         value: production
#       - key: APP_KEY
#         value: "sua-chave-app-key"
#       - key: DB_CONNECTION
#         value: pgsql
#       - key: DB_HOST
#         value: "db"  # Este é o nome do serviço de banco de dados
#       - key: DB_PORT
#         value: "5432"
#       - key: DB_DATABASE
#         value: "dbteste_wmug"
#       - key: DB_USERNAME
#         value: "root"
#       - key: DB_PASSWORD
#         value: "5g0uiB2k7xrEhWLfP75YknN77HkHqx70"

#   - type: database
#     name: postgres
#     plan: free
#     environment:
#       POSTGRES_DB: dbteste_wmug
#       POSTGRES_USER: root
#       POSTGRES_PASSWORD: 5g0uiB2k7xrEhWLfP75YknN77HkHqx70

# networks:
#   app-network:
#     driver: bridge

services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php artisan serve --host=0.0.0.0 --port=8000

